"""SQLAlchemy models for core database tables."""
from datetime import datetime
from typing import Optional
from uuid import uuid4
from sqlalchemy import (
    Column, String, Text, Boolean, Float, DateTime, JSON,
    ForeignKey, Index
)
from sqlalchemy.dialects.postgresql import UUID, JSONB
from core.database import Base


class PathMapping(Base):
    """Path mapping between local and cloud file systems."""
    
    __tablename__ = "path_mappings"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)
    local_path = Column(Text, nullable=False, unique=True, index=True)
    cloud_path = Column(Text, nullable=False)
    cloud_id = Column(Text, index=True)
    cloud_provider = Column(String(50), nullable=False, default="google_drive")
    file_type = Column(String(50))
    last_synced_at = Column(DateTime(timezone=True))
    created_at = Column(DateTime(timezone=True), default=datetime.utcnow)
    updated_at = Column(DateTime(timezone=True), default=datetime.utcnow, onupdate=datetime.utcnow)


class UserPreference(Base):
    """User preferences and settings."""
    
    __tablename__ = "user_preferences"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)
    user_id = Column(String(255), nullable=False, unique=True)
    preferences = Column(JSONB, nullable=False, default={})
    created_at = Column(DateTime(timezone=True), default=datetime.utcnow)
    updated_at = Column(DateTime(timezone=True), default=datetime.utcnow, onupdate=datetime.utcnow)


class UserBehaviorEvent(Base):
    """User behavior tracking for proactive modeling."""
    
    __tablename__ = "user_behavior_events"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)
    user_id = Column(String(255), nullable=False, index=True)
    event_type = Column(String(100), nullable=False, index=True)
    event_data = Column(JSONB, nullable=False)
    context = Column(JSONB)
    timestamp = Column(DateTime(timezone=True), default=datetime.utcnow, index=True)


class Task(Base):
    """Task management."""
    
    __tablename__ = "tasks"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)
    user_id = Column(String(255), nullable=False, index=True)
    title = Column(Text, nullable=False)
    description = Column(Text)
    status = Column(String(50), default="pending", index=True)
    priority = Column(String(20), default="medium")
    source_type = Column(String(100))
    source_id = Column(Text)
    due_date = Column(DateTime(timezone=True), index=True)
    completed_at = Column(DateTime(timezone=True))
    created_at = Column(DateTime(timezone=True), default=datetime.utcnow)
    updated_at = Column(DateTime(timezone=True), default=datetime.utcnow, onupdate=datetime.utcnow)


class ProactiveSuggestion(Base):
    """Proactive suggestions generated by the system."""
    
    __tablename__ = "proactive_suggestions"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)
    user_id = Column(String(255), nullable=False, index=True)
    suggestion_type = Column(String(100), nullable=False)
    title = Column(Text, nullable=False)
    description = Column(Text)
    action_data = Column(JSONB, nullable=False)
    confidence_score = Column(Float)
    status = Column(String(50), default="pending", index=True)
    user_response = Column(String(50))
    responded_at = Column(DateTime(timezone=True))
    created_at = Column(DateTime(timezone=True), default=datetime.utcnow)


class ChatSession(Base):
    """Chat session tracking."""
    
    __tablename__ = "chat_sessions"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)
    user_id = Column(String(255), nullable=False)
    session_data = Column(JSONB, nullable=False)
    active = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), default=datetime.utcnow)
    updated_at = Column(DateTime(timezone=True), default=datetime.utcnow, onupdate=datetime.utcnow)


class AutomationRule(Base):
    """Workflow automation rules."""
    
    __tablename__ = "automation_rules"
    
    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid4)
    user_id = Column(String(255), nullable=False)
    rule_name = Column(String(255), nullable=False)
    trigger_type = Column(String(100), nullable=False)
    trigger_config = Column(JSONB, nullable=False)
    action_type = Column(String(100), nullable=False)
    action_config = Column(JSONB, nullable=False)
    enabled = Column(Boolean, default=True)
    created_at = Column(DateTime(timezone=True), default=datetime.utcnow)
    updated_at = Column(DateTime(timezone=True), default=datetime.utcnow, onupdate=datetime.utcnow)
