#!/bin/bash
# Quick Commit Helper for Personal Workspace
# Automates PR creation and auto-merge for sessions/ and .claude/ directories
#
# Usage: ./scripts/quick-commit.sh "Your commit message"
#
# Requirements:
# - GitHub CLI (gh) installed and authenticated
# - PAT token with 'repo' scope configured

set -e  # Exit on error

# Configuration
PERSONAL_PATHS=("sessions/" ".claude/")
BASE_BRANCH="main"
MESSAGE="${1:-Personal workspace update}"
BRANCH="quick-$(date +%s)"

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'  # No Color

echo -e "${YELLOW}🚀 Quick Commit Helper${NC}"
echo "Branch: $BRANCH"
echo "Message: $MESSAGE"
echo ""

# Check if gh CLI is installed
if ! command -v gh &> /dev/null; then
    echo -e "${RED}❌ Error: GitHub CLI (gh) is not installed${NC}"
    echo "Install from: https://cli.github.com/"
    exit 1
fi

# Check if authenticated
if ! gh auth status &> /dev/null; then
    echo -e "${RED}❌ Error: Not authenticated with GitHub CLI${NC}"
    echo "Run: gh auth login"
    exit 1
fi

# Save current branch
CURRENT_BRANCH=$(git branch --show-current)
echo "Current branch: $CURRENT_BRANCH"

# Check for unstaged changes in personal workspace
CHANGES_FOUND=false
for path in "${PERSONAL_PATHS[@]}"; do
    if git status --porcelain "$path" | grep -q .; then
        CHANGES_FOUND=true
        echo -e "${GREEN}✓${NC} Found changes in: $path"
    fi
done

if [ "$CHANGES_FOUND" = false ]; then
    echo -e "${YELLOW}⚠️  No changes detected in personal workspace directories${NC}"
    echo "Paths checked: ${PERSONAL_PATHS[*]}"
    exit 0
fi

# Create new branch
echo ""
echo -e "${YELLOW}Creating branch: $BRANCH${NC}"
git checkout -b "$BRANCH"

# Add personal workspace files
echo -e "${YELLOW}Staging changes...${NC}"
for path in "${PERSONAL_PATHS[@]}"; do
    if [ -d "$path" ] || [ -f "$path" ]; then
        git add "$path"
    fi
done

# Show staged changes
echo ""
echo -e "${YELLOW}Staged changes:${NC}"
git status --short

# Commit
echo ""
echo -e "${YELLOW}Creating commit...${NC}"
git commit -m "$MESSAGE"

# Push
echo -e "${YELLOW}Pushing to remote...${NC}"
git push origin "$BRANCH"

# Create PR
echo ""
echo -e "${YELLOW}Creating Pull Request...${NC}"
PR_URL=$(gh pr create \
    --base "$BASE_BRANCH" \
    --title "Personal workspace: $MESSAGE" \
    --body "🤖 Auto-generated PR for personal workspace files

**Changes:**
- Sessions and/or Claude workspace updates

**Paths:**
$(for path in "${PERSONAL_PATHS[@]}"; do echo "- \`$path\`"; done)

**Auto-merge:** This PR will be automatically approved and merged.

---
Generated by: \`scripts/quick-commit.sh\`" \
    --label "personal-workspace" \
    --label "auto-merge")

echo -e "${GREEN}✅ PR created: $PR_URL${NC}"

# Approve PR
echo -e "${YELLOW}Approving PR...${NC}"
gh pr review --approve "$PR_URL"
echo -e "${GREEN}✅ PR approved${NC}"

# Auto-merge PR
echo -e "${YELLOW}Enabling auto-merge...${NC}"
gh pr merge --auto --squash --delete-branch "$PR_URL"
echo -e "${GREEN}✅ Auto-merge enabled${NC}"

# Return to original branch
echo ""
echo -e "${YELLOW}Returning to branch: $CURRENT_BRANCH${NC}"
git checkout "$CURRENT_BRANCH"

echo ""
echo -e "${GREEN}✅ Done!${NC}"
echo ""
echo "Summary:"
echo "  - Created branch: $BRANCH"
echo "  - Created PR: $PR_URL"
echo "  - Approved and set to auto-merge"
echo "  - Branch will be automatically deleted after merge"
echo ""
echo "The PR will merge automatically once all status checks pass."
