# Quick Commit Helper for Personal Workspace (PowerShell)
# Automates PR creation and auto-merge for sessions/ and .claude/ directories
#
# Usage: .\scripts\quick-commit.ps1 "Your commit message"
#        .\scripts\quick-commit.ps1 -Message "Your commit message"
#
# Requirements:
# - GitHub CLI (gh) installed and authenticated
# - PAT token with 'repo' scope configured

param(
    [Parameter(Position=0)]
    [string]$Message = "Personal workspace update"
)

$ErrorActionPreference = "Stop"

# Configuration
$PersonalPaths = @("sessions/", ".claude/")
$BaseBranch = "main"
$Branch = "quick-$(Get-Date -Format 'yyyyMMddHHmmss')"

Write-Host "🚀 Quick Commit Helper" -ForegroundColor Yellow
Write-Host "Branch: $Branch"
Write-Host "Message: $Message"
Write-Host ""

# Check if gh CLI is installed
try {
    $null = Get-Command gh -ErrorAction Stop
} catch {
    Write-Host "❌ Error: GitHub CLI (gh) is not installed" -ForegroundColor Red
    Write-Host "Install from: https://cli.github.com/"
    exit 1
}

# Check if authenticated
$authStatus = gh auth status 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Host "❌ Error: Not authenticated with GitHub CLI" -ForegroundColor Red
    Write-Host "Run: gh auth login"
    exit 1
}

# Save current branch
$CurrentBranch = git branch --show-current
Write-Host "Current branch: $CurrentBranch"

# Check for unstaged changes in personal workspace
$ChangesFound = $false
foreach ($path in $PersonalPaths) {
    $status = git status --porcelain $path 2>&1
    if ($status) {
        $ChangesFound = $true
        Write-Host "✓ Found changes in: $path" -ForegroundColor Green
    }
}

if (-not $ChangesFound) {
    Write-Host "⚠️  No changes detected in personal workspace directories" -ForegroundColor Yellow
    Write-Host "Paths checked: $($PersonalPaths -join ', ')"
    exit 0
}

# Create new branch
Write-Host ""
Write-Host "Creating branch: $Branch" -ForegroundColor Yellow
git checkout -b $Branch

# Add personal workspace files
Write-Host "Staging changes..." -ForegroundColor Yellow
foreach ($path in $PersonalPaths) {
    if ((Test-Path $path)) {
        git add $path
    }
}

# Show staged changes
Write-Host ""
Write-Host "Staged changes:" -ForegroundColor Yellow
git status --short

# Commit
Write-Host ""
Write-Host "Creating commit..." -ForegroundColor Yellow
git commit -m $Message

# Push
Write-Host "Pushing to remote..." -ForegroundColor Yellow
git push origin $Branch

# Create PR
Write-Host ""
Write-Host "Creating Pull Request..." -ForegroundColor Yellow

$prBody = @"
🤖 Auto-generated PR for personal workspace files

**Changes:**
- Sessions and/or Claude workspace updates

**Paths:**
$(foreach ($path in $PersonalPaths) { "- ``$path``" })

**Auto-merge:** This PR will be automatically approved and merged.

---
Generated by: ``scripts/quick-commit.ps1``
"@

$prUrl = gh pr create `
    --base $BaseBranch `
    --title "Personal workspace: $Message" `
    --body $prBody `
    --label "personal-workspace" `
    --label "auto-merge"

Write-Host "✅ PR created: $prUrl" -ForegroundColor Green

# Approve PR
Write-Host "Approving PR..." -ForegroundColor Yellow
gh pr review --approve $prUrl
Write-Host "✅ PR approved" -ForegroundColor Green

# Auto-merge PR
Write-Host "Enabling auto-merge..." -ForegroundColor Yellow
gh pr merge --auto --squash --delete-branch $prUrl
Write-Host "✅ Auto-merge enabled" -ForegroundColor Green

# Return to original branch
Write-Host ""
Write-Host "Returning to branch: $CurrentBranch" -ForegroundColor Yellow
git checkout $CurrentBranch

Write-Host ""
Write-Host "✅ Done!" -ForegroundColor Green
Write-Host ""
Write-Host "Summary:"
Write-Host "  - Created branch: $Branch"
Write-Host "  - Created PR: $prUrl"
Write-Host "  - Approved and set to auto-merge"
Write-Host "  - Branch will be automatically deleted after merge"
Write-Host ""
Write-Host "The PR will merge automatically once all status checks pass."
